unvariance/collector

.github/workflows/ci.yml, docs/index.md, mkdocs.yml
- Added initial documentation for memory-collector using mkdocs. For now have copied the contents of readme.md to index.md
- Added workflow to publish pages when a new push is made to main branch.
- Currently theme for published pages is default material UI as shown below:
=> #10 Adding initial documentation for memory-collector

.github/workflows/docs-workflow.yml, mkdocs.yml
- Removed unused local dependency
Also nektos/act is failing on my local machine as CI is pushing commit to gh-pages branch which I do not have write access to. Rest all looks good, so should now be good to review.
=> fixes #10: Removed unused dependency of awesome-pages

.github/workflows/docs-workflow.yml
- Removed unwanted content read permission as it is erroneous to have two content permission statement.
=> fixes #10: Removed unwanted content read permission

docs/architecture/decisions/2024-12-21-container-notifications.md
=> Add WIP of architecture decision for notification of container lifecycle events

.github/workflows/ci-collector.yaml, .github/workflows/ci-cpi-count.yaml, cmd/collector/Dockerfile, cmd/cpi-count/Dockerfile
Created a CI lifecycle for both components:
- `ci-collector.yaml` --> CI for Collector component.
- `ci-cpi-count.yaml` --> CI for CPI-Count component.
- Added `Dockerfile` for both separately.
- Cache and push in the Build and push step in the above workflows will work when Dockerhub Container registry/any other container registry provided (I will need to modify if it is not DockerHub). Need to add a login step as well when the container registry is created.
- Docker tag `latest` will be created automatically when the image is build from the default branch (`main` in your case).
- Please let me know if you need anything else I will add it :)
=> Memory Collector CI

docs/collection.md
This is a draft specification of what the collector should measure initially. The idea is to create a data-set that would show contention and would inform how to calculate interference signals.
thanks @atimeofday for discussing this last week!
=> add discussion of collection strategy

.github/workflows/aws-runner-template.yaml, docs/ci/aws-setup.md
This adds a template Actions workflow in `.github/workflows/aws-runner-template.yaml`, and a document in `docs/ci/aws-setup.md`
=> Add AWS configuration for GitHub Actions and doc

.github/workflows/get-resctrl-and-perf-info.yaml
This adds an action that retrieves information from resctrl. It is set to run on a bare metal machine with Intel RDT.
=> Get resctrl perf status

.github/workflows/test-ebpf-collector.yaml, Dockerfile.devcontainer, cmd/collector/.gitignore, cmd/collector/gen.go, cmd/collector/go.mod, cmd/collector/go.sum, cmd/collector/main.go, cmd/collector/task_counter.c
=> Add skeleton eBPF-based collector that interfaces the kernel module

module/memory_collector.c, module/memory_collector_trace.h, module/test_module.sh
=> allocate RMIDs to processes

module/memory_collector.c, module/resctrl.c, module/resctrl.h
=> Write task RMIDs to MSRs on context switches

docs/noise-generators.md
=> Add noise generator documentation

README.md
=> Remove repo rename notices

docs/architecture/decisions/2025-02-18-getting-cmt-measurements.md
Issue #46 tries to find how to use perf to read these measurements, but we found that was not available in the kernel. Instead, we choose to build a kernel module to gather this information.
closes #46
=> Created decision record for how to read CMT measurements

module/memory_collector.c, module/resctrl.c
=> Add support for emulated RMIDs

docs/design.md, module/rmid_allocator.c, module/rmid_allocator.h
=> add limbo time to freed RMIDs

.github/workflows/test-ebpf-collector.yaml, cmd/collector/main.go, cmd/collector/task_counter.c, module/collector_main.c, module/tracepoints.h
=> send measurement deltas from eBPF to userspace

cmd/collector/main.go, pkg/aggregate/aggregator.go, pkg/aggregate/aggregator_test.go
=> add RMID-based measurement aggregation

.github/workflows/test-ebpf-collector.yaml, cmd/collector/main.go
Also fixed initialization order in collector, so RMID metadata arrives first
=> add RMID data to parquet

.github/workflows/test-kernel-module.yaml, module/Makefile, module/README.md, module/collector_main.c, module/rmid_allocator.c, module/rmid_allocator.h, module/rmid_allocator_test.c, module/test_rmid_allocator.sh
=> refactor kernel RMID allocator for testability and add tests

.github/workflows/test-kernel-module.yaml, module/Makefile, module/README.md, module/benchmark_sync_timer.sh, module/benchmark_sync_timer_stress.sh, module/collector_main.c, module/sync_timer.c, module/sync_timer.h, module/sync_timer_benchmark.c, module/sync_timer_test.c, module/test_sync_timer.sh
=> refactor sync timer component, add tests and benchmark

.github/workflows/test-kernel-module.yaml, module/visualize_benchmark.R
- Ended up creating a 2x4 array of plots, which gives good horizontal and vertical resolution.
- Added 500ms snippets for higher time resolution
- Plot Survival Density Function to compare the distributions and tails
closes #96
=> Improve sync timer visualization

.github/workflows/test-kernel-module.yaml, module/combine_baselines.py, module/sync_timer_test.c, module/test_procfs.sh, module/test_rmid_allocator.sh, module/test_sync_timer.sh
simplify kernel tests, fix timer destroy test, add script for experiment plotting
=> add script to combine baseline sync-timer measurements from multiple experiments

pkg/backoff/.gitignore, pkg/backoff/README.md, pkg/backoff/backoff.h, pkg/backoff/backoff_test.bpf.c, pkg/backoff/backoff_test.go
=> Implement eBPF Backoff Mechanism for RMID Allocation

Cargo.lock, Cargo.toml, crates/collector/Cargo.toml, crates/collector/src/bpf/collector.bpf.c, crates/collector/src/bpf/collector.h, crates/collector/src/main.rs, crates/perf_events/Cargo.toml, crates/perf_events/src/dispatcher.rs, crates/perf_events/src/lib.rs, crates/perf_events/src/reader.rs
=> Implement Event Dispatcher for perf_events crate

Cargo.lock, Cargo.toml, crates/collector/src/main.rs, crates/timeslot/Cargo.toml, crates/timeslot/src/lib.rs, crates/timeslot/src/min_tracker.rs
=> MinTracker: Track minimum completed time slot across all CPUs

crates/collector/src/bpf/collector.bpf.c, crates/collector/src/bpf/collector.h, crates/collector/src/main.rs
=> Migrate Perf Counter Collection from Go to Rust Implementation

.github/workflows/deploy-k3-environment.yaml, kustomize/kustomization.yaml
I used Kustomize to modify the resource values in the microservices deployment YAML files. The kustomization.yaml file in Kustomize allows us to adjust resource settings for each pod as needed.
=> Kustomize to Change resource values

.github/workflows/build-collector.yaml, Dockerfile.collector
=> Create CI workflow for ebpf collector

.gitignore, Cargo.lock, Cargo.toml, crates/collector/Cargo.toml, crates/collector/src/main.rs, crates/collector/src/parquet_writer.rs, crates/collector/src/parquet_writer_task.rs, crates/collector/src/task_metadata.rs, crates/collector/src/timeslot_data.rs
=> Add Object Store Support to Memory Collector

.github/actions/aws-runner/action.yml, .github/workflows/test-ebpf-collector.yaml, crates/collector/src/main.rs, crates/collector/src/parquet_writer.rs, docs/s3-testing.md
=> add S3 bucket writing tests with IAM and key-based authentication

.github/workflows/tag-collector-latest.yaml, .github/workflows/test-helm-chart.yaml, charts/collector/Chart.yaml, charts/collector/README.md, charts/collector/templates/NOTES.txt, charts/collector/templates/_helpers.tpl, charts/collector/templates/clusterrole.yaml, charts/collector/templates/clusterrolebinding.yaml, charts/collector/templates/collector.yaml, charts/collector/templates/secret.yaml, charts/collector/templates/serviceaccount.yaml, charts/collector/values.yaml, crates/collector/src/main.rs
=> Add helm chart and chart test

.github/workflows/publish-helm-chart.yaml, README.md, charts/collector/README.md
=> Add helm chart publishing workflow

Cargo.lock, Cargo.toml, crates/nri/Cargo.toml, crates/nri/build.rs, crates/nri/src/api.proto, crates/nri/src/examples.rs, crates/nri/src/lib.rs
=> add NRI ttrpc bindings in a new NRI crate

Cargo.lock, Cargo.toml, crates/nri/Cargo.toml, crates/nri/build.rs, crates/nri/src/lib.rs, crates/nri/src/multiplex.rs, crates/nri/tests/integration_test.rs
=> Implement NRI socket multiplexer

.github/workflows/benchmark.yaml, .github/workflows/make-docs-to-gh-pages.yml, .github/workflows/publish-benchmark-to-gh.yaml, docs/benchmark.md, mkdocs.yml
=> Automatically publish benchmark results to GitHub Pages

Dockerfile.devcontainer, scripts/plot_cpi_by_llc_misses.R, scripts/simulation-of-high-res-vs-low-res-measurements.R
- add scatter plot of CPI as a function of memory bandwidth
- add plot of simulation with high and low resolution reporting (used in presetntations)
- fix devcontainer's rust installation
=> add visualizations and fix devcontainer

.github/workflows/test-ebpf-collector.yaml, Cargo.lock, crates/bpf/Cargo.toml, crates/bpf/src/bpf/sync_timer.bpf.h, crates/bpf/src/lib.rs, crates/bpf/src/sync_timer.rs
=> tighten error handling in sync timer initialization

charts/collector/values.yaml
solves part of the requirements for #190
=> document permissions and ensure sufficient permissions for timer migration setting

.github/workflows/test-nri-integration.yaml, Cargo.lock, crates/nri/Cargo.toml, crates/nri/src/events_mask.rs, crates/nri/src/lib.rs, crates/nri/src/metadata.rs, crates/nri/src/multiplex.rs, crates/nri/tests/README.md, crates/nri/tests/integration_test.rs, crates/nri/tests/nri_plugin_test.rs
=> Implement NRI plugin for container metadata collection to channel

.github/workflows/benchmark.yaml, deploy/opentelemetry-demo/values.yaml
=> feat(benchmark): use auto-scaling in bare-metal benchmark workflow

crates/bpf/src/bpf/collector.bpf.c, crates/bpf/src/bpf/collector.h, crates/collector/src/bpf_perf_to_trace.rs, crates/collector/src/main.rs, crates/collector/src/perf_event_processor.rs
=> feat(collector): add trace bpf handler and CLI flag support

.github/workflows/test-helm-chart.yaml, charts/collector/README.md, charts/collector/templates/collector.yaml, charts/collector/values.yaml, crates/collector/src/bpf_perf_to_trace.rs
=> feat(charts): add support for trace configuration to chart

.github/workflows/benchmark.yaml, .github/workflows/publish-benchmark-to-gh.yaml
=> feat(benchmark): add trace collection to benchmark

.github/workflows/benchmark.yaml, .github/workflows/test-ebpf-collector.yaml
=> ci: fix permissions for PR checks

crates/bpf/src/lib.rs, crates/perf_events/src/dispatcher.rs, crates/perf_events/src/reader.rs
goal is to eliminate cases of events being read out of order.
=> fix(collector): more conservative event ordering in perf ring reader

crates/collector/src/bpf_error_handler.rs, crates/collector/src/main.rs, crates/collector/src/perf_event_processor.rs
=> perf: reduce bpf blocking using lost samples events
