unvariance/collector

cmd/cpi-count/.gitignore
cmd/cpi-count/go.mod
cmd/cpi-count/go.sum
cmd/cpi-count/goperf.go
cmd/cpi-count/main.go
cmd/cpi-count/perf.go
cmd/cpi-count/perf_test.go

This patch addresses #23 .
It adds a new binary, `cpi-count`, that measures an artificial CPU-bound workload using two methods:
- Linux `perf`
- `elastic/go-perf` library
When run, the binary prints out the measured cycles, instructions, and CPI, using both methods:
```bash
$ go build . && sudo ./cpi-count
2024/12/25 13:26:10 GoPerf Cycles: 523916886, GoPerf Instrs: 2040367688, GoPerf CPI: 0.256776
2024/12/25 13:26:10 PerfCmd Cycles: 560685244, PerfCmd Instrs: 2094182633, PerfCmd CPI: 0.267735
```
The program is arranged in a simple, symmetric manner:
- Start measurement `perf`
- Start workload and measurement using `go-perf`
- Stop `go-perf` measurement
- Stop `perf` measurement.
A test is also provided that asserts that the measured cycles, instructions, and CPI are similar across both …

feat: Add binary & test comparing output of Linux `perf` and `elastic/go-perf` library

---

cmd/collector/collector_test.go

Addendum to PR #27, comments out a sleep call to reduce integration test time to complete by 10x / 1s but remain present as a reminder in case something related to initialization time breaks

Disable unnecessary(?) sleep in integration test

---

.github/workflows/ci-collector.yaml
.github/workflows/ci-cpi-count.yaml

Memory Collector CI Modifications:
1. Added the GHCR repo name --> `<repository_name>/<container_image_name>` --> In our case: `ghcr.io/memory-collector/cpi-count` and `ghcr.io/memory-collector/collector`.
2. Authentication to **GHCR** instead of **DockerHub**.
3. Fixed the push to my side-branch to the actual `main`, my bad sorry about that.
4. Also added **docker build cache** so the build would take less and get some of the layers at least from cache and not rebuild them from scratch each time.
These changes should ensure the images would be build into GHCR of this project respectively.

Memory Collector CI Modifications

---

docs/architecture/decisions/2025-01-02-aws-test-runners.md

Solves #4.
The document surveys the different options for running test on multiple AWS instances, and decides to use the EC2 CLI to spin up instances that use the User Data mechanism to run Github Action Runners. The test itself then runs on that runner.
Issue #31 then specifies the first such Action to run `cpi-count`.

Add AWS test runners decision document

---

.github/workflows/Prometheus Integration Test.yml

Resolves #21. This worked on my fork, but review and/or testing is welcome to confirm whether it properly returns the test pass and fail cases, particularly after setting up Go and compiling correctly.

Add GitHub Action for Prometheus Integration Test

---

.github/workflows/cpi-count-test.yaml
justfile

This patch adds a new workflow, `cpi-count-test.yaml`. This workflow is based on the one created in #38.
The `cpi-count-test.yaml` workflow spins up a self-hosted Github runner on an `c5.9xlarge` EC2 instance, checks out this repository, and executes the `cpi-count` binary and tests. The runner is torn down once the workflow is complete.
Setting `perf_event_paranoid=0` worked fine, and so the program and tests can be run without `sudo` (which would have otherwise complicated things).
The workflow only has a `workflow_dispatch` trigger (i.e., can only be run manually).
Here is an example of a successful run: https://github.com/tverghis/memory-collector/actions/runs/12880226002
Closes #31.
Edit: This section is now obsolete because AWS was able to increase the quota to 128 vCPUs, thereby …

Add workflow to test `cpi-count` on EC2 runners

---

docs/ci/aws-setup.md

Applied the new policy to the IAM role, added doc.
closes #41

add IAM role instructions to allow spot instance creation

---

.github/workflows/cpi-count-test.yaml

The [upstream] `ec2-github-runner` action does not yet support provisioning Spot instances for runners. There is an open PR, but it seems to have stagnated. I've opened a [new PR](https://github.com/machulav/ec2-github-runner/pull/210) with the same changes, but until that gets merged, we can use the same patch from [my own fork](https://github.com/tverghis/ec2-github-runner/tree/spot-instance).
[upstream]: https://github.com/machulav/ec2-github-runner

Use a patched version of the `ec2-github-runner` action to provision runners on Spot instances

---

.github/workflows/aws-runner-template.yaml
.github/workflows/cpi-count-test.yaml

- Experimented with removing some of the `permissions` and was able to remove two in the AWS template and in the CPI AWS tests.
- Fixed the version of ec2-github-runner to the new version supporting spot
Verified both workflows work, and use spot instances (on the AWS console)

Reduce permissions and fix version in AWS Actions

---

docs/cmt-perf.md

add doc about intel-cat-cmt's perf code

---

.devcontainer.json
.github/workflows/test-kernel-module.yaml
Dockerfile.devcontainer
module/Makefile
module/README.md
module/dkms.conf
module/memory_collector.c

This adds a minimal kernel module, a Makefile, a Dev Container configuration that allows making the module, and a Github Action to test loading and unloading in an Ubuntu AMI

Add-skeleton-kernel-module

---

cmd/bpftracer/main.go
cmd/bpftracer/unvariance_bpftracer.bt

Addresses 3/4 of Issue #36 
Next step: GitHub Actions container image workflow to run/test the monitor. I would like to discuss this a bit tomorrow if possible.
Let me know if anything else needs done before merging this.

Initial eBPF instrumentation to track process context switches, V1 bpftrace prototype

---

.github/workflows/demo.yaml
scripts/plot_llc_misses.R

The previous plots used `geom_area` which smoothed out the measurements. Switched to `geom_col`.
Added 0.3 second and 0.5 second plots to better show detail on smaller screens

Improve showing volatility in LLC miss plots

---

.github/actions/aws-runner/action.yml
.github/actions/aws-runner/cleanup/action.yml
.github/workflows/benchmark.yaml
.github/workflows/demo.yaml
deploy/opentelemetry-demo/values.yaml
scripts/plot_cpi_by_llc_misses.R
scripts/plot_workload_performance.R

This PR addresses scaling the OpenTelemetry demo benchmark to support higher workloads. Below is a summary of the changes implemented:
- **Multi-region support for self-hosted runners**: Increased reliability of spot instance allocation by adding support for multiple regions
- **Replica scaling**: 
- Increased the number of replicas across the system
- Implemented non-uniform scaling for services with different requirements
- **Memory limit adjustments**:
- Increased memory limits that were previously set too low
- Applied different memory limits for different pods based on their needs
- **Performance enhancement**: Switched from HTTP User (Locust interface) to Fast HTTP User to reduce overhead
- **Statistics output**: 
- Grouped product accesses together instead of having one per URL
- …

Scale OpenTelemetry demo benchmark to achieve higher CPU utilization

---

.github/workflows/test-ebpf-collector.yaml
crates/bpf/src/bpf/collector.bpf.c
crates/bpf/src/bpf/sync_timer.bpf.h
crates/bpf/src/lib.rs
crates/bpf/src/sync_timer.rs
crates/collector/src/main.rs

closes #182
- add kernels 5.15 and 5.10 to multi-kernel tests
- display parquet files when kernel test successful
- improve logging when BPF load fails: use the log crate and add a debug log on failure
- add legacy support for relative timers
- removed bpf_map_lookup_percpu_elem dependency (that required 5.19+)

add support for relative timers, down to kernel 5.15

---

crates/collector/src/main.rs

This patch converts all outstanding use of `println!` and `eprintln!` macros in the `collector` crate to `debug!`/`info!`/`error!` from the `log` crate. It also changes some `info!`s to `debug!`s based on these requirements from the issue:
```
Most initialization and setup messages should use debug!
Only key information (like successful start confirmation) should use info!
``` 
Implements part of the work required for #173

(crates/collector) Use logging framework instead of `println/eprintln`

---

crates/bpf/src/bpf/collector.bpf.c
crates/bpf/src/lib.rs
crates/perf_events/src/dispatcher.rs

When message timestamps are collected a lot in advance of sending the message, userspace can decide to process a message that will be later (because it will see that message first).
1. move the timestamp computation as close as we could to sending the perf measurement so the race window is reduced
2. add an explicit grace period before current time, where userspace will not read messages  that are closer than that period, in case a message took that long to send. If all messages take less than the grace period to send, they will be processed in order.

fix(collector): reduce time window for non-monotonicity, add timing grace window

---

.github/workflows/get-resctrl-and-perf-info.yaml

Adds comprehensive listing of /sys/fs/resctrl files and domain counts to the get-resctrl-and-perf-info workflow to help identify cache and memory bandwidth domains on different EC2 instance types.

ci: add resctrl domain listing to debug workflow

---

.github/workflows/test-resctrl-e2e.yaml
.github/workflows/test-resctrl.yaml
Cargo.lock
Cargo.toml
crates/resctrl/Cargo.toml
crates/resctrl/README.md
crates/resctrl/src/error.rs
crates/resctrl/src/lib.rs
crates/resctrl/src/provider.rs
crates/resctrl/tests/smoke_test.rs

Summary
- Add new resctrl crate with safe APIs (create/delete groups, assign/list tasks) and domain error model (NotMounted, NoPermission, Capacity, Io) behind FsProvider abstraction.
- Add integration smoke test (tests/smoke_test.rs) gated by RESCTRL_E2E=1 for hardware runs; unit tests use a mock filesystem provider.
- Add GitHub Actions workflow (test-resctrl.yaml):
- Build + unit tests on GitHub-hosted runner; build only the resctrl smoke test binary and upload it as artifact.
- Provision m7i.metal-24xl spot EC2 runner via existing aws-runner composite action and run the smoke binary there (mounts resctrl if needed).
- Triggers: manual (workflow_dispatch) and push to main on relevant paths (crates/resctrl/**, workflow file, workspace Cargo.toml).
Notes
- Uses existing secrets: …

add resctrl crate

---

cmd/bpftracer/main.go
cmd/prometheus_metrics/collector_test.go
cmd/prometheus_metrics/main.go
cmd/prometheus_metrics/record_metrics.go
crates/trace-analysis/src/analyzer.rs
crates/trace-analysis/src/concurrency_analysis.rs
crates/trace-analysis/src/main.rs

Ran `cargo fmt --all` and `go fmt ./...` to apply standard formatting across the Rust workspace and Go modules.
No functional changes; formatting only.

chore: format codebase
